server:
  port: 8081

spring:
  rabbitmq:
    request:
      host: localhost
      port: 5672
      username: guest
      password: guest
      exchenge:
        producer: ex.producer.news
      routing-key:
        producer: rk.producer.news
      deadletter:
        producer: dl.producer.news